### ISSUE TITLE
review

### ISSUE THREAD

**Issue by kazqvaizer** [shmonoff/Fogstream#1]
https://github.com/shmonoff/Fogstream/blob/606421687fe5780dc1f9625962184db044511fbd/exam-1/02-mvc-solution/exam-01.py#L1

В целом код жизнеспособный, но перегружен,  KISS. Вариант MVC в данной простой задаче - непозволительная роскошь, т.к. необходимо было реализовать пару тройку функций для совершения простых действий без особой интерактивности, т.к. это не было задано в условиях. Есть сомнительные решения в виде 4 вложенных while 1, которые убивают читаемость и понимание кода. Вместо батарей ифов, всегда лучше использовать словари.

**Comment by shmonoff** [comment]
@kazqvaizer, спасибо за замечания! сначала реализовал процедурный вариант, не понравилось. работа по шаблону вызывает сплошное удовольствие.
читабельнось постараюсь улучшить...
